### ISSUE TITLE
fix: Build fail on windows

### ISSUE THREAD

**Issue by filiph** [alnitak/flutter_soloud#121]
**Description**

I'm not 100% sure this is a flutter_soloud issue but I'm reporting it anyway just in case, while I'm sitting at my Windows PC.

When building or running a flutter_soloud-using project on Windows, I get a build error:

```
$ flutter run -d windows --verbose

[... the usual warnings ...]

[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
[        ]   D:\dev\giant_robot\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\filters\smbPitchShift.cpp(450,68): warning C4244: '+=': conversion from 'double' to 'float', possible loss of data
[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
[        ] "D:\dev\giant_robot\build\windows\x64\INSTALL.vcxproj" (default target) (1) ->
[        ] "D:\dev\giant_robot\build\windows\x64\ALL_BUILD.vcxproj" (default target) (3) ->
[        ] "D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj" (default target) (7) ->
[        ] (ClCompile target) ->
[        ]   D:\dev\giant_robot\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\filters\smbPitchShift.cpp(254,25): error C2065: 'M_PI_2': undeclared identifier
[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
[        ]   D:\dev\giant_robot\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\filters\smbPitchShift.cpp(275,21): error C2065: 'M_PI_2': undeclared identifier
[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
[        ]     14 Warning(s)
[        ]     2 Error(s)
[        ] Time Elapsed 00:00:10.06
[  +10 ms] Building Windows application... (completed in 10.4s)
[        ] Error: Build process failed.
[   +1 ms] "flutter run" took 11,085ms.
[  +72 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:874:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1408:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:420:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>


[  +21 ms] ensureAnalyticsSent: 19ms
[        ] Running 2 shutdown hooks
[   +7 ms] Shutdown hooks complete
[  +21 ms] exiting with code 1
```

The error isn't shown in red here on GitHub, so I'll duplicate it here:

```
[        ]   D:\dev\giant_robot\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\filters\smbPitchShift.cpp(254,25): error C2065: 'M_PI_2': undeclared identifier
[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
[        ]   D:\dev\giant_robot\windows\flutter\ephemeral\.plugin_symlinks\flutter_soloud\src\filters\smbPitchShift.cpp(275,21): error C2065: 'M_PI_2': undeclared identifier
[D:\dev\giant_robot\build\windows\x64\plugins\flutter_soloud\flutter_soloud_plugin.vcxproj]
```

Without `--verbose`, the build fails like this:

```
Building Windows application...                                    26.8s
Error: Build process failed.
```

**Steps To Reproduce**

(I can give you access to the repo, @alnitak.) 

**Expected Behavior**

The app builds and runs.

**Additional Context**

I have just upgraded to latest Flutter and dependencies. I did run `flutter clean` for good measure. `flutter_soloud` is at `2.1.0`.

**Comment by filiph** [comment]
Closing as duplicate of https://github.com/alnitak/flutter_soloud/issues/120
